type: Dataplane
mesh: default
name: {{ DP_NAME }}
networking:
  address: {{ ADDRESS }}
  gateway:
    tags:
      kuma.io/service: gateway
  transparentProxying:
    redirectPortInbound: 15006
    redirectPortOutbound: 15001
