---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=63e7a206892601b733cfc8cd81ee5e46dbf4e78a
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=63e7a206892601b733cfc8cd81ee5e46dbf4e78a

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
